input_file: data/ftrs_test_data.ftrs
# input_file: data/maxquant_test_data.txt
masses_file: data/masses/e_coli_monomer_masses.csv
ppm_tolerance: 0.5
time_delta: 10
mod_list:
  - Sodium
  - Potassium
  - Anhydro
  - DeAc
  - Deacetyl_Anhydro
  - Nude
  - Decay
  - Amidation
  - Amidase
  - Double_Anh
  - multimers_Glyco
output_dir: output
warnings: ignore
quiet: false
float_format: 4
